### ISSUE TITLE
Using Yt as server always redownloads files.

### ISSUE THREAD

**Issue by watermelvin** [Benexl/FastAnime#32]
It would be very nice if the Yt server also performed the check that the gogoanime server performs to see if there is an existing file rather than always redownloading and overwriting the file.

**Comment by Benexl** [comment]
Its not the server that checks its yt-dlp, so this ain't possible. Though i'll try investigating further.

**Comment by watermelvin** [comment]
I saw that in another issue someone mentioned a downloads db, I think that would also close this issue.

**Comment by Benexl** [comment]
Am gonna close this one then
