### ISSUE TITLE
[Feature] override config for sub/dub for the download CLI command

### ISSUE THREAD

**Issue by serialjaywalker** [Benexl/FastAnime#41]
There are times when both subs _and_ dubs are desired for a series. Currently (to my knowledge), you must update the config before downloading again. This may also require adding the sub/dub label if the override is used to prevent overwriting episodes if left in the default download dir.

**Comment by Benexl** [comment]
Actually that exists just undocumented
Use `--help` to discover cli options

Gonna right a wiki early next year
